branches:
  only:
  - master
  - stable
  - gpg2
language: java
jdk:
- openjdk14
dist: focal
before_install:
install:
- mvn clean install -Dgpg.skip=true
- "./ci/deploy.sh"
before_script: 
script: 
after_success:
after_failure:
